# Generated by Django 3.1.1 on 2020-09-15 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='formfile',
            options={'verbose_name': 'Form file', 'verbose_name_plural': 'Form files'},
        ),
    ]
